name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automasdsftically triggered by a ${{ github.event_name }} event."
