name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automasdsftically triggered by a ${{ github.event_name }} event."
